/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AgentDashboardPlugin
});
module.exports = __toCommonJS(main_exports);

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  directoriesInitialized: false,
  llmModel: "",
  llmModelFast: "",
  llmEmbedModel: "",
  collisionMin: 0.6,
  collisionMax: 0.75,
  enableVectorCollision: false,
  archiveDays: 30,
  rssFeeds: ""
};
var CognitionHubSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const s = this.plugin.settings;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("模型配置（全部可选，留空则文本任务走 Claudian）").setHeading();
    new import_obsidian.Setting(containerEl).setName("大模型 LLM_MODEL").setDesc("精加工/洞见生成。留空走 Claudian 会话默认模型。").addText((t) => t.setValue(s.llmModel).onChange(async (v) => {
      s.llmModel = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("小模型 LLM_MODEL_FAST").setDesc("读文件/预处理/批量。可用国产模型省额度。").addText((t) => t.setValue(s.llmModelFast).onChange(async (v) => {
      s.llmModelFast = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("概念碰撞").setHeading();
    new import_obsidian.Setting(containerEl).setName("启用向量碰撞增强").setDesc("关闭时用关键词/标签轻量碰撞（零 key）。开启需填 embedding 模型。").addToggle((t) => t.setValue(s.enableVectorCollision).onChange(async (v) => {
      s.enableVectorCollision = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (s.enableVectorCollision) {
      new import_obsidian.Setting(containerEl).setName("Embedding 模型 LLM_EMBED_MODEL").setDesc("向量碰撞用。云端 API，无需本地模型。").addText((t) => t.setValue(s.llmEmbedModel).onChange(async (v) => {
        s.llmEmbedModel = v.trim();
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("碰撞甜区下限").setDesc("低于此值视为无关（默认 0.6）").addText((t) => t.setValue(String(s.collisionMin)).onChange(async (v) => {
      const n = Number(v);
      if (!isNaN(n)) {
        s.collisionMin = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("碰撞甜区上限").setDesc("高于此值视为重复（默认 0.75）").addText((t) => t.setValue(String(s.collisionMax)).onChange(async (v) => {
      const n = Number(v);
      if (!isNaN(n)) {
        s.collisionMax = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("归档与 RSS").setHeading();
    new import_obsidian.Setting(containerEl).setName("归档清理期限（天）").setDesc("归档文件停留超过此天数移入 .trash/ 待确认（默认 30）").addText((t) => t.setValue(String(s.archiveDays)).onChange(async (v) => {
      const n = Number(v);
      if (!isNaN(n) && n > 0) {
        s.archiveDays = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("RSS 源列表").setDesc("每行一个 URL，仅拉取 Markdown 内容到 03-参考资料").addTextArea((t) => {
      t.setValue(s.rssFeeds);
      t.inputEl.addClass("cognition-hub-textarea-tall");
      t.onChange(async (v) => {
        s.rssFeeds = v;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/data/vaultReader.ts
var import_obsidian2 = require("obsidian");
function strVal(fm, key) {
  const v = fm?.[key];
  if (typeof v === "string") return v;
  if (typeof v === "number") return String(v);
  return "";
}
function arrStr(fm, key) {
  const v = fm?.[key];
  if (Array.isArray(v)) return v.map((x) => String(x));
  if (typeof v === "string" && v.trim()) return [v];
  return [];
}
var VALID_SOURCES = ["外部输入", "发散", "解决问题"];
var VaultReader = class {
  constructor(app) {
    this.app = app;
  }
  async readInspirations() {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith("00-灵感库/"));
    const out = [];
    for (const file of files) {
      const fm = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (!fm || fm.type !== "inspiration") continue;
      const src = strVal(fm, "source");
      const status = strVal(fm, "status") || "pending";
      out.push({
        path: file.path,
        body: await this.readBody(file),
        source: VALID_SOURCES.includes(src) ? src : "发散",
        status: status === "carded" ? "carded" : "pending",
        captured: strVal(fm, "captured"),
        tags: arrStr(fm, "tags"),
        cardRef: strVal(fm, "card_ref") || void 0
      });
    }
    return out;
  }
  async readBody(file) {
    const raw = await this.app.vault.cachedRead(file);
    const m = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
    const body = m ? raw.slice(m[0].length) : raw;
    return body.trim();
  }
  readCards() {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith("01-项目/") || f.path.startsWith("02-长期关注/"));
    const out = [];
    for (const file of files) {
      const fm = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (!fm || fm.type !== "card") continue;
      const dir = file.path.startsWith("01-项目/") ? "01-项目" : "02-长期关注";
      out.push({
        path: file.path,
        title: strVal(fm, "title"),
        sourceRef: arrStr(fm, "source_ref"),
        tags: arrStr(fm, "tags"),
        wiki: strVal(fm, "wiki") || "",
        created: strVal(fm, "created"),
        targetDir: dir
      });
    }
    return out;
  }
  readConcepts() {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith("06-Wiki/concepts/"));
    const out = [];
    for (const file of files) {
      const fm = this.app.metadataCache.getFileCache(file)?.frontmatter;
      if (!fm) continue;
      out.push({
        path: file.path,
        title: strVal(fm, "title") || file.basename,
        discipline: strVal(fm, "discipline"),
        sources: arrStr(fm, "sources"),
        related: arrStr(fm, "related")
      });
    }
    return out;
  }
  async readReviewItems() {
    const file = this.app.vault.getAbstractFileByPath("07-系统/review.md");
    if (!(file instanceof import_obsidian2.TFile)) return [];
    const raw = await this.app.vault.cachedRead(file);
    const out = [];
    for (const line of raw.split("\n")) {
      const m = line.match(/^\s*-\s*\[([ xX])\]\s+(.*)$/);
      if (!m) continue;
      out.push({ checked: (m[1] ?? "").toLowerCase() === "x", text: (m[2] ?? "").trim() });
    }
    return out;
  }
  async readPipelineLog(limit) {
    const file = this.app.vault.getAbstractFileByPath("07-系统/pipeline-log.md");
    if (!(file instanceof import_obsidian2.TFile)) return [];
    const raw = await this.app.vault.cachedRead(file);
    const lines = raw.split("\n").map((l) => l.trimEnd()).filter((l) => l.trim().length > 0);
    return lines.slice(Math.max(0, lines.length - limit));
  }
};

// src/data/timeGroup.ts
var BUCKET_ORDER = ["今天", "昨天", "本周内", "更早"];
function capturedDate(captured) {
  const datePart = (captured || "").trim().split(" ")[0] ?? "";
  const m = datePart.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return null;
  const d = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  return isNaN(d.getTime()) ? null : d;
}
function dayDiff(a, b) {
  const da = new Date(a.getFullYear(), a.getMonth(), a.getDate()).getTime();
  const db = new Date(b.getFullYear(), b.getMonth(), b.getDate()).getTime();
  return Math.round((db - da) / 864e5);
}
function bucketOf(captured, now) {
  const d = capturedDate(captured);
  if (!d) return "更早";
  const diff = dayDiff(d, now);
  if (diff <= 0) return "今天";
  if (diff === 1) return "昨天";
  if (diff <= 6) return "本周内";
  return "更早";
}
function groupByTime(items, now) {
  const buckets = {
    "今天": [],
    "昨天": [],
    "本周内": [],
    "更早": []
  };
  for (const it of items) {
    buckets[bucketOf(it.captured, now)].push(it);
  }
  const groups = [];
  for (const label of BUCKET_ORDER) {
    const arr = buckets[label];
    if (arr.length === 0) continue;
    arr.sort((a, b) => (b.captured || "").localeCompare(a.captured || ""));
    groups.push({ label, items: arr });
  }
  return groups;
}
function countSources(items) {
  const external = items.filter((i) => i.source === "外部输入").length;
  const divergent = items.filter((i) => i.source === "发散").length;
  const problem = items.filter((i) => i.source === "解决问题").length;
  return { external, divergent, problem, total: items.length };
}

// src/views/tabs/InspirationTab.ts
var import_obsidian3 = require("obsidian");
var SOURCE_CLASS = {
  "外部输入": "src-external",
  "发散": "src-divergent",
  "解决问题": "src-problem"
};
function renderInspirationTab(container, inspirations, plugin, app) {
  const counts = countSources(inspirations);
  const pendingCount = inspirations.filter((i) => i.status === "pending").length;
  const cardedCount = inspirations.filter((i) => i.status === "carded").length;
  renderHeader(container, plugin);
  renderSourceBar(container, counts);
  renderCounts(container, pendingCount, cardedCount);
  if (inspirations.length === 0) {
    const empty = container.createDiv({ cls: "cognition-empty-state" });
    empty.createDiv({ text: "还没有灵感", cls: "cognition-empty-title" });
    empty.createDiv({ text: "点右上角「捕获」记录第一个念头", cls: "cognition-empty-hint" });
    return;
  }
  renderTimeline(container, inspirations, plugin, app);
}
function renderHeader(c, plugin) {
  const header = c.createDiv({ cls: "cognition-header" });
  header.createEl("h2", { text: "灵感库", cls: "cognition-title" });
  const btn = header.createEl("button", { cls: "cognition-capture-btn" });
  btn.createSpan({ text: "⚡", cls: "cognition-capture-icon" });
  btn.createSpan({ text: "捕获" });
  btn.onclick = () => plugin.openCapture();
}
function renderSourceBar(c, counts) {
  const wrap = c.createDiv({ cls: "cognition-source-bar" });
  if (counts.total === 0) return;
  const segs = [
    ["src-external", counts.external],
    ["src-divergent", counts.divergent],
    ["src-problem", counts.problem]
  ];
  for (const [cls, n] of segs) {
    if (n === 0) continue;
    const seg = wrap.createDiv({ cls: `cognition-source-seg ${cls}` });
    seg.setCssProps({ "flex-grow": String(n) });
    seg.setAttribute("aria-label", `${n}`);
  }
}
function renderCounts(c, pending, carded) {
  const row = c.createDiv({ cls: "cognition-counts" });
  row.createSpan({ text: `待加工 ${pending}`, cls: "cognition-count-pending" });
  row.createSpan({ text: "·", cls: "cognition-count-dot" });
  row.createSpan({ text: `已转卡片 ${carded}`, cls: "cognition-count-carded" });
}
function renderTimeline(c, inspirations, plugin, app) {
  const timeline = c.createDiv({ cls: "cognition-timeline" });
  const groups = groupByTime(inspirations, /* @__PURE__ */ new Date());
  for (const group of groups) {
    const g = timeline.createDiv({ cls: "cognition-tl-group" });
    const anchor = g.createDiv({ cls: "cognition-tl-anchor" });
    anchor.createSpan({ cls: "cognition-tl-node" });
    anchor.createSpan({ text: group.label, cls: "cognition-tl-label" });
    for (const item of group.items) renderInspiration(g, item, plugin, app);
  }
}
function renderInspiration(parent, item, plugin, app) {
  const row = parent.createDiv({ cls: "cognition-tl-item" });
  if (item.status === "carded") row.addClass("is-carded");
  row.createSpan({ cls: `cognition-tl-bar ${SOURCE_CLASS[item.source]}` });
  const card = row.createDiv({ cls: "cognition-insp" });
  const firstLine = (item.body.split("\n")[0] ?? "").slice(0, 80);
  card.createDiv({ text: firstLine || "(无正文)", cls: "cognition-insp-body" });
  const meta = card.createDiv({ cls: "cognition-insp-meta" });
  meta.createSpan({ text: item.source, cls: SOURCE_CLASS[item.source] });
  const time = shortTime(item.captured);
  if (time) meta.createSpan({ text: time, cls: "cognition-insp-time" });
  if (item.status === "carded") {
    meta.createSpan({ text: "→ 卡片", cls: "cognition-insp-badge" });
  } else {
    const expandBtn = meta.createEl("button", { text: "🤖 扩写", cls: "cognition-expand-btn" });
    expandBtn.onclick = (ev) => {
      ev.stopPropagation();
      openExpandMenu(ev, item, plugin);
    };
  }
  row.onclick = () => {
    void app.workspace.openLinkText(item.path, "", false);
  };
}
function openExpandMenu(ev, item, plugin) {
  const menu = new import_obsidian3.Menu();
  menu.addItem((mi) => mi.setTitle("扩写到 01-项目").onClick(() => {
    void plugin.expandInspiration(item.path, "01-项目");
  }));
  menu.addItem((mi) => mi.setTitle("扩写到 02-长期关注").onClick(() => {
    void plugin.expandInspiration(item.path, "02-长期关注");
  }));
  menu.showAtMouseEvent(ev);
}
function shortTime(captured) {
  const s = (captured || "").trim();
  const parts = s.split(" ");
  if (parts.length === 2) return parts[1] ?? "";
  const dm = (parts[0] ?? "").match(/^\d{4}-(\d{2}-\d{2})$/);
  return dm ? dm[1] ?? "" : s;
}

// src/data/stats.ts
function pad(n) {
  return String(n).padStart(2, "0");
}
function ymd(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function capturedYMD(captured) {
  const part = (captured || "").trim().split(" ")[0] ?? "";
  return /^\d{4}-\d{2}-\d{2}$/.test(part) ? part : null;
}
function buildHeatmap(items, now, weeks = 12) {
  const byDay = /* @__PURE__ */ new Map();
  for (const it of items) {
    const key = capturedYMD(it.captured);
    if (key) byDay.set(key, (byDay.get(key) ?? 0) + 1);
  }
  const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  end.setDate(end.getDate() + (6 - end.getDay()));
  const start = new Date(end);
  start.setDate(start.getDate() - (weeks * 7 - 1));
  const weeksOut = [];
  let max = 0, total = 0;
  const cursor = new Date(start);
  for (let w = 0; w < weeks; w++) {
    const cells = [];
    for (let d = 0; d < 7; d++) {
      const key = ymd(cursor);
      const count = byDay.get(key) ?? 0;
      if (count > max) max = count;
      total += count;
      cells.push({ date: key, count });
      cursor.setDate(cursor.getDate() + 1);
    }
    weeksOut.push({ cells });
  }
  return { weeks: weeksOut, max, total };
}
function sourceDistribution(items) {
  const external = items.filter((i) => i.source === "外部输入").length;
  const divergent = items.filter((i) => i.source === "发散").length;
  const problem = items.filter((i) => i.source === "解决问题").length;
  return { external, divergent, problem, total: items.length };
}
function coreCounts(items, now) {
  const total = items.length;
  const pending = items.filter((i) => i.status === "pending").length;
  const carded = items.filter((i) => i.status === "carded").length;
  const weekAgo = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  weekAgo.setDate(weekAgo.getDate() - 6);
  const weekAgoKey = ymd(weekAgo);
  const thisWeek = items.filter((i) => {
    const k = capturedYMD(i.captured);
    return k !== null && k >= weekAgoKey;
  }).length;
  return { total, pending, carded, thisWeek };
}
function topTags(items, limit = 12) {
  const byTag = /* @__PURE__ */ new Map();
  for (const it of items) {
    for (const t of it.tags) {
      const tag = (t || "").trim();
      if (!tag) continue;
      byTag.set(tag, (byTag.get(tag) ?? 0) + 1);
    }
  }
  return Array.from(byTag.entries()).map(([tag, count]) => ({ tag, count })).sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag)).slice(0, limit);
}

// src/views/tabs/OverviewTab.ts
function renderOverviewTab(container, inspirations) {
  const now = /* @__PURE__ */ new Date();
  container.createEl("h2", { text: "概览", cls: "cognition-title" });
  renderCoreCounts(container, coreCounts(inspirations, now));
  renderHeatmap(container, buildHeatmap(inspirations, now, 12));
  renderSourceDist(container, sourceDistribution(inspirations));
  renderTags(container, topTags(inspirations, 12));
}
function section(parent, title) {
  const sec = parent.createDiv({ cls: "cognition-ov-section" });
  sec.createDiv({ text: title, cls: "cognition-ov-title" });
  return sec.createDiv({ cls: "cognition-ov-body" });
}
function renderCoreCounts(c, cc) {
  const body = section(c, "核心计数");
  const grid = body.createDiv({ cls: "cognition-count-grid" });
  const cards = [
    ["总灵感", cc.total],
    ["待加工", cc.pending],
    ["已转卡片", cc.carded],
    ["本周新增", cc.thisWeek]
  ];
  for (const [label, val] of cards) {
    const card = grid.createDiv({ cls: "cognition-count-card" });
    card.createDiv({ text: String(val), cls: "cognition-count-num" });
    card.createDiv({ text: label, cls: "cognition-count-label" });
  }
}
function renderHeatmap(c, hm) {
  const body = section(c, `捕获热力图 · 近 12 周（共 ${hm.total} 条）`);
  const grid = body.createDiv({ cls: "cognition-heat-grid" });
  for (const week of hm.weeks) {
    const col = grid.createDiv({ cls: "cognition-heat-week" });
    for (const cell of week.cells) {
      const level = heatLevel(cell.count, hm.max);
      const box = col.createDiv({ cls: `cognition-heat-cell heat-l${level}` });
      box.setAttribute("aria-label", `${cell.date}: ${cell.count}`);
      box.setAttribute("title", `${cell.date} · ${cell.count} 条`);
    }
  }
}
function heatLevel(count, max) {
  if (count === 0) return 0;
  if (max <= 1) return 4;
  const r = count / max;
  if (r <= 0.25) return 1;
  if (r <= 0.5) return 2;
  if (r <= 0.75) return 3;
  return 4;
}
function renderSourceDist(c, sd) {
  const body = section(c, "来源分布");
  if (sd.total === 0) {
    body.createDiv({ text: "暂无数据", cls: "cognition-ov-empty" });
    return;
  }
  const rows = [
    ["外部输入", "src-external", sd.external],
    ["发散", "src-divergent", sd.divergent],
    ["解决问题", "src-problem", sd.problem]
  ];
  for (const [label, cls, n] of rows) {
    const row = body.createDiv({ cls: "cognition-dist-row" });
    row.createSpan({ text: label, cls: `cognition-dist-label ${cls}` });
    const track = row.createDiv({ cls: "cognition-dist-track" });
    const fill = track.createDiv({ cls: `cognition-dist-fill ${cls}` });
    const pct = sd.total > 0 ? Math.round(n / sd.total * 100) : 0;
    fill.setCssProps({ width: `${pct}%` });
    row.createSpan({ text: `${n}`, cls: "cognition-dist-val" });
  }
}
function renderTags(c, tags) {
  const body = section(c, "高频标签");
  if (tags.length === 0) {
    body.createDiv({ text: "暂无标签", cls: "cognition-ov-empty" });
    return;
  }
  const cloud = body.createDiv({ cls: "cognition-tag-cloud" });
  const maxCount = tags[0]?.count ?? 1;
  for (const t of tags) {
    const chip = cloud.createSpan({ cls: "cognition-tag-chip" });
    chip.createSpan({ text: t.tag, cls: "cognition-tag-name" });
    chip.createSpan({ text: String(t.count), cls: "cognition-tag-count" });
    const scale = maxCount > 0 ? 0.8 + 0.35 * (t.count / maxCount) : 1;
    chip.setCssProps({ "font-size": `${scale.toFixed(2)}em` });
  }
}

// src/views/tabs/PipelineTab.ts
async function renderPipelineTab(container, plugin, app) {
  container.createEl("h2", { text: "管线 / Review", cls: "cognition-title" });
  const reader = new VaultReader(app);
  const cards = reader.readCards();
  const reviewItems = await reader.readReviewItems();
  const log = await reader.readPipelineLog(5);
  renderActions(container, plugin, app);
  renderQueued(container, cards, plugin);
  renderReview(container, reviewItems);
  renderLog(container, log);
}
function section2(parent, title) {
  const sec = parent.createDiv({ cls: "cognition-pl-section" });
  sec.createDiv({ text: title, cls: "cognition-pl-title" });
  return sec.createDiv({ cls: "cognition-pl-body" });
}
function renderActions(c, plugin, app) {
  const body = section2(c, "一键操作");
  const row = body.createDiv({ cls: "cognition-pl-actions" });
  const ingestBtn = row.createEl("button", { text: "▶ 运行增量 ingest", cls: "cognition-pl-btn" });
  ingestBtn.onclick = () => {
    void ingestAllQueued(plugin, app);
  };
  const collideBtn = row.createEl("button", { text: "◉ 运行碰撞检测", cls: "cognition-pl-btn is-disabled" });
  collideBtn.disabled = true;
  collideBtn.setAttribute("title", "Phase 3B 开放");
  const reviewBtn = row.createEl("button", { text: "▶ 处理 Review", cls: "cognition-pl-btn" });
  reviewBtn.onclick = () => {
    void plugin.processReview();
  };
}
async function ingestAllQueued(plugin, app) {
  const reader = new VaultReader(app);
  const queued = reader.readCards().filter((cd) => cd.wiki === "queued");
  for (const cd of queued) await plugin.ingestCard(cd.path);
}
function renderQueued(c, cards, plugin) {
  const queued = cards.filter((cd) => cd.wiki === "queued");
  const body = section2(c, `待 ingest 卡片 (${queued.length})`);
  if (queued.length === 0) {
    body.createDiv({ text: "暂无待入库卡片", cls: "cognition-pl-empty" });
    return;
  }
  for (const cd of queued) {
    const row = body.createDiv({ cls: "cognition-pl-card" });
    row.createSpan({ text: cd.title || cd.path, cls: "cognition-pl-card-title" });
    const btn = row.createEl("button", { text: "🧠 ingest", cls: "cognition-pl-card-btn" });
    btn.onclick = () => {
      void plugin.ingestCard(cd.path);
    };
  }
}
function renderReview(c, items) {
  const body = section2(c, `待审核 Review (${items.length})`);
  if (items.length === 0) {
    body.createDiv({ text: "暂无待审核项", cls: "cognition-pl-empty" });
    return;
  }
  for (const it of items) {
    const row = body.createDiv({ cls: "cognition-pl-review" });
    row.createSpan({ text: it.checked ? "☑" : "☐", cls: "cognition-pl-check" });
    row.createSpan({ text: it.text, cls: "cognition-pl-review-text" });
  }
}
function renderLog(c, log) {
  const body = section2(c, "最近管线日志");
  if (log.length === 0) {
    body.createDiv({ text: "暂无运行记录", cls: "cognition-pl-empty" });
    return;
  }
  for (const line of log) {
    body.createDiv({ text: line, cls: "cognition-pl-log-line" });
  }
}

// src/views/DashboardView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_DASHBOARD = "cognition-hub-view";
var TABS = [
  { id: "inspiration", label: "灵感库" },
  { id: "overview", label: "概览" },
  { id: "pipeline", label: "管线" }
];
var DashboardView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.activeTab = "inspiration";
    this.reader = new VaultReader(this.app);
  }
  getViewType() {
    return VIEW_TYPE_DASHBOARD;
  }
  getDisplayText() {
    return "认知生产台";
  }
  getIcon() {
    return "lightbulb";
  }
  async onOpen() {
    await this.refresh();
  }
  async onClose() {
    this.contentEl.empty();
  }
  async refresh() {
    const c = this.contentEl;
    c.empty();
    c.addClass("cognition-dashboard");
    const inspirations = await this.reader.readInspirations();
    this.renderTabBar(c);
    const tabBody = c.createDiv({ cls: "cognition-tab-body" });
    await this.renderActiveTab(tabBody, inspirations);
  }
  renderTabBar(c) {
    const bar = c.createDiv({ cls: "cognition-tabbar" });
    for (const tab of TABS) {
      const btn = bar.createDiv({
        cls: `cognition-tab${tab.id === this.activeTab ? " is-active" : ""}`,
        text: tab.label
      });
      btn.onclick = () => {
        if (this.activeTab === tab.id) return;
        this.activeTab = tab.id;
        void this.refresh();
      };
    }
  }
  async renderActiveTab(body, inspirations) {
    if (this.activeTab === "overview") {
      renderOverviewTab(body, inspirations);
    } else if (this.activeTab === "pipeline") {
      await renderPipelineTab(body, this.plugin, this.app);
    } else {
      renderInspirationTab(body, inspirations, this.plugin, this.app);
    }
  }
};

// src/modals/QuickCaptureModal.ts
var import_obsidian5 = require("obsidian");
var SOURCES = ["外部输入", "发散", "解决问题"];
var QuickCaptureModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("cognition-capture-modal");
    contentEl.createEl("h3", { text: "快速捕获灵感" });
    const data = { body: "", source: "发散", tags: [] };
    new import_obsidian5.Setting(contentEl).setName("灵感正文").addTextArea((t) => {
      t.setPlaceholder("记录你的灵感、反思或问题…").onChange((v) => {
        data.body = v;
      });
      t.inputEl.addClass("cognition-hub-textarea-med");
    });
    new import_obsidian5.Setting(contentEl).setName("来源").addDropdown((d) => {
      for (const s of SOURCES) d.addOption(s, s);
      d.setValue("发散").onChange((v) => {
        data.source = v;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("标签").setDesc("逗号分隔，可选").addText(
      (t) => t.setPlaceholder("例如：认知, 阅读").onChange((v) => {
        data.tags = v.split(",").map((x) => x.trim()).filter(Boolean);
      })
    );
    new import_obsidian5.Setting(contentEl).addButton(
      (b) => b.setButtonText("取消").onClick(() => this.close())
    ).addButton(
      (b) => b.setButtonText("捕获").setCta().onClick(() => {
        if (!data.body.trim()) return;
        this.close();
        this.onSubmit(data);
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/data/inspirationWriter.ts
var ILLEGAL = /[\\/:*?"<>|#^[\]]/g;
function slugify(text) {
  const firstLine = (text.split("\n")[0] || "").trim();
  const cleaned = firstLine.replace(ILLEGAL, "").replace(/\s+/g, "-").trim();
  const truncated = cleaned.slice(0, 30).replace(/-+$/, "");
  return truncated || "inspiration";
}
function pad2(n) {
  return String(n).padStart(2, "0");
}
function fmtDate(d) {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}
function fmtStamp(d) {
  return `${fmtDate(d)} ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}
function fileStamp(d) {
  return `${fmtDate(d)}-${pad2(d.getHours())}${pad2(d.getMinutes())}`;
}
function yamlList(items) {
  if (items.length === 0) return "[]";
  return "[" + items.map((t) => JSON.stringify(t)).join(", ") + "]";
}
function buildInspiration(input, now) {
  const slug = slugify(input.body);
  const path = `00-灵感库/${fileStamp(now)}-${slug}.md`;
  const fm = [
    "---",
    "type: inspiration",
    `source: ${input.source}`,
    "status: pending",
    `captured: ${fmtStamp(now)}`,
    `tags: ${yamlList(input.tags)}`,
    "---"
  ].join("\n");
  const content = `${fm}

${input.body.trim()}
`;
  return { path, content };
}

// src/data/triggers.ts
function pad3(n) {
  return String(n).padStart(2, "0");
}
function stampCompact(d) {
  return `${d.getFullYear()}${pad3(d.getMonth() + 1)}${pad3(d.getDate())}-${pad3(d.getHours())}${pad3(d.getMinutes())}${pad3(d.getSeconds())}`;
}
function stampReadable(d) {
  return `${d.getFullYear()}-${pad3(d.getMonth() + 1)}-${pad3(d.getDate())} ${pad3(d.getHours())}:${pad3(d.getMinutes())}:${pad3(d.getSeconds())}`;
}
function yamlScalar(v) {
  if (v === "" || /[:#[\]{}&*!|>'"%@`,]/.test(v) || /^\s|\s$/.test(v)) {
    return JSON.stringify(v);
  }
  return v;
}
function buildTrigger(action, params, now) {
  const path = `07-系统/.ingest-triggers/${action}-${stampCompact(now)}.md`;
  const lines = ["---", `action: ${action}`];
  for (const [k, v] of Object.entries(params)) {
    lines.push(`${k}: ${yamlScalar(v)}`);
  }
  lines.push(`created: ${stampReadable(now)}`);
  lines.push("---");
  lines.push("");
  return { path, content: lines.join("\n") + "\n" };
}

// src/main.ts
var import_obsidian6 = require("obsidian");
var AgentDashboardPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    await this.ensureDirectories();
    this.registerView(
      VIEW_TYPE_DASHBOARD,
      (leaf) => new DashboardView(leaf, this)
    );
    this.addRibbonIcon("lightbulb", "打开认知生产台", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-dashboard",
      name: "打开面板",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "quick-capture-inspiration",
      name: "快速捕获灵感",
      callback: () => {
        this.openCapture();
      }
    });
    this.addSettingTab(new CognitionHubSettingTab(this.app, this));
  }
  onunload() {
  }
  async ensureDirectories() {
    const requiredDirs = [
      "00-灵感库",
      "01-项目",
      "02-长期关注",
      "03-参考资料",
      "04-归档",
      "04-归档/.trash",
      "05-Skills",
      "06-Wiki",
      "06-Wiki/concepts",
      "06-Wiki/entities",
      "06-Wiki/sources",
      "06-Wiki/syntheses",
      "06-Wiki/graph",
      "07-系统",
      "07-系统/.ingest-triggers",
      "08-创作"
    ];
    for (const dir of requiredDirs) {
      if (!this.app.vault.getAbstractFileByPath(dir)) {
        await this.app.vault.createFolder(dir).catch(() => {
        });
      }
    }
    if (!this.settings.directoriesInitialized) {
      this.settings.directoriesInitialized = true;
      await this.saveSettings();
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_DASHBOARD, active: true });
        leaf = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD)[0];
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  openCapture() {
    new QuickCaptureModal(this.app, (data) => {
      void (async () => {
        const file = buildInspiration(data, /* @__PURE__ */ new Date());
        try {
          await this.app.vault.create(file.path, file.content);
        } catch {
          new import_obsidian6.Notice(`捕获失败：无法创建文件 ${file.path}（可能已存在同名文件）`);
          return;
        }
        await this.refreshDashboards();
      })();
    }).open();
  }
  async refreshDashboards() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD)) {
      const view = leaf.view;
      if (view.refresh) await view.refresh();
    }
  }
  async writeTrigger(action, params) {
    const tf = buildTrigger(action, params, /* @__PURE__ */ new Date());
    try {
      await this.app.vault.create(tf.path, tf.content);
      return true;
    } catch {
      new import_obsidian6.Notice(`触发失败：无法写入 ${tf.path}（可能已存在同名触发文件，请稍后重试）`);
      return false;
    }
  }
  async expandInspiration(sourcePath, targetDir) {
    const ok = await this.writeTrigger("expand", { source: sourcePath, target_dir: targetDir });
    if (ok) {
      new import_obsidian6.Notice("已排队扩写为卡片，下次 Agent 会话将处理");
      await this.refreshDashboards();
    }
  }
  async ingestCard(sourcePath) {
    const ok = await this.writeTrigger("ingest", { source: sourcePath });
    if (ok) new import_obsidian6.Notice("已排队 ingest，下次 Agent 会话将处理");
  }
  async processReview() {
    const ok = await this.writeTrigger("review", {});
    if (ok) new import_obsidian6.Notice("已排队处理 Review，下次 Agent 会话将执行");
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
